#!/bin/sh

##############################################################################
# tobackup - A simple unix-style backup tool
# Author : Thomas Martin <thomas@oopss.org>
##############################################################################

usage() {
    cat <<EOT >&2
Usage: $0 [OPTION] HOST EMAIL

 -f FILE : specify alternative config file (default /usr/local/etc/backuprc)
 -d DEPTH : print DEPTH levels of last backup content

 HOST : host referenced in config file
 EMAIL : where to send reports

EOT
}

conffile="/usr/local/etc/backuprc"

while getopts 'f:d:' opt; do
    case $opt in
    f)
        conffile=$OPTARG
        ;;
    d)
        backup_detail_depth=$OPTARG
        ;;
    esac
done
shift $((OPTIND-1))

if [ $# -ne 2 ]; then
    usage
    exit 1
fi

. $conffile
backuphost=$1
email=$2

mailbody=`mktemp /tmp/mailbody.XXXXXX`
exec >$mailbody

cat <<EOT
======================
Backup archives report
======================

EOT

print_size() {
    size=`du -sh $1 | cut -f 1`
    mtime_timestamp=$(stat -c "%Y" $1)
    mtime=$(date -d @$mtime_timestamp '+%Y/%m/%d')
    printf "%s = %s\n" $mtime $size
}

for subdir in daily weekly monthly; do
    fullsubdir="/home/backup/$backuphost/$subdir"
    if [ -d $fullsubdir ]; then
        echo "Archives $subdir :"
        cd $fullsubdir
        for i in [0-9]; do
            print_size $i
        done
        echo
    fi
done

print_backup_detail() {
    backuphost=$1
    depth=$2

cat <<EOT

Last backup (first-level directories)
=====================================
EOT

    cd /home/backup/$backuphost/daily/0
    find . -maxdepth $depth -type d
}

if [ $backup_detail_depth ]; then
    print_backup_detail $backuphost $backup_detail_depth
fi

mail -s "[$backuphost] backup report" $email <$mailbody

